import React, { useState } from 'react';
import {
  Download,
  FileText,
  FileCode,
  Printer,
  Copy,
  Check,
  X,
  FileJson,
} from 'lucide-react';

export default function ExportModal({ isOpen, onClose, data }) {
  const [copied, setCopied] = useState(false);

  if (!isOpen || !data) return null;

  const { metadata, summary, summary_length, key_points, main_ideas, improvement_suggestions } = data;

  const generateMarkdown = () => {
    return `# Document Analysis Report: ${metadata?.filename || 'Document'}

**Generated By:** Document Summary Assistant (AI-Powered)  
**File Type:** ${metadata?.file_type?.toUpperCase()}  
**Word Count:** ${metadata?.word_count || 0}  
**Summary Mode:** ${summary_length?.toUpperCase() || 'MEDIUM'}  

---

## 1. Executive Summary
${summary}

---

## 2. Key Points
${(key_points || []).map((pt, i) => `${i + 1}. ${pt}`).join('\n')}

---

## 3. Main Ideas & Document Sections
${(main_ideas || []).map((idea) => `### ${idea.title}\n${idea.summary}\n`).join('\n')}

---

## 4. Improvement Suggestions
${(improvement_suggestions || [])
  .map(
    (sug) =>
      `- **[${sug.category?.toUpperCase() || 'GENERAL'}]** (${sug.severity?.toUpperCase()} priority): ${sug.suggestion}`
  )
  .join('\n')}
`;
  };

  const downloadFile = (content, filename, type) => {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleDownloadMarkdown = () => {
    const md = generateMarkdown();
    const baseName = (metadata?.filename || 'summary').replace(/\.[^/.]+$/, '');
    downloadFile(md, `${baseName}_summary.md`, 'text/markdown;charset=utf-8;');
  };

  const handleDownloadTxt = () => {
    const md = generateMarkdown();
    const baseName = (metadata?.filename || 'summary').replace(/\.[^/.]+$/, '');
    downloadFile(md, `${baseName}_summary.txt`, 'text/plain;charset=utf-8;');
  };

  const handleDownloadJson = () => {
    const jsonStr = JSON.stringify(data, null, 2);
    const baseName = (metadata?.filename || 'summary').replace(/\.[^/.]+$/, '');
    downloadFile(jsonStr, `${baseName}_analysis.json`, 'application/json;charset=utf-8;');
  };

  const handlePrint = () => {
    window.print();
  };

  const handleCopyReport = () => {
    const md = generateMarkdown();
    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="bg-white dark:bg-slate-900 rounded-3xl shadow-2xl border border-slate-200 dark:border-slate-800 w-full max-w-lg overflow-hidden">
        
        {/* Header */}
        <div className="px-6 py-4 border-b border-slate-100 dark:border-slate-800 flex items-center justify-between">
          <div className="flex items-center space-x-2.5">
            <div className="w-8 h-8 rounded-xl bg-brand-500/10 dark:bg-brand-500/20 text-brand-600 dark:text-brand-400 flex items-center justify-center">
              <Download className="w-4 h-4" />
            </div>
            <h3 className="text-base font-semibold text-slate-900 dark:text-white">
              Export Analysis Report
            </h3>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded-lg text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Options List */}
        <div className="p-6 space-y-3">
          <button
            type="button"
            onClick={handleDownloadMarkdown}
            className="w-full flex items-center justify-between p-4 rounded-2xl bg-slate-50 hover:bg-brand-50/50 dark:bg-slate-800/60 dark:hover:bg-brand-950/30 border border-slate-200/80 dark:border-slate-700 hover:border-brand-400 transition-all text-left group"
          >
            <div className="flex items-center space-x-3.5">
              <div className="w-10 h-10 rounded-xl bg-blue-100 dark:bg-blue-950/60 text-blue-600 dark:text-blue-400 flex items-center justify-center">
                <FileText className="w-5 h-5" />
              </div>
              <div>
                <p className="text-sm font-bold text-slate-900 dark:text-white group-hover:text-brand-600 dark:group-hover:text-brand-400 transition-colors">
                  Markdown Document (.md)
                </p>
                <p className="text-xs text-slate-500 dark:text-slate-400">
                  Formatted for Notion, Obsidian, GitHub, or documentation
                </p>
              </div>
            </div>
            <Download className="w-4 h-4 text-slate-400 group-hover:text-brand-500 transition-colors" />
          </button>

          <button
            type="button"
            onClick={handleDownloadTxt}
            className="w-full flex items-center justify-between p-4 rounded-2xl bg-slate-50 hover:bg-brand-50/50 dark:bg-slate-800/60 dark:hover:bg-brand-950/30 border border-slate-200/80 dark:border-slate-700 hover:border-brand-400 transition-all text-left group"
          >
            <div className="flex items-center space-x-3.5">
              <div className="w-10 h-10 rounded-xl bg-emerald-100 dark:bg-emerald-950/60 text-emerald-600 dark:text-emerald-400 flex items-center justify-center">
                <FileCode className="w-5 h-5" />
              </div>
              <div>
                <p className="text-sm font-bold text-slate-900 dark:text-white group-hover:text-brand-600 dark:group-hover:text-brand-400 transition-colors">
                  Plain Text File (.txt)
                </p>
                <p className="text-xs text-slate-500 dark:text-slate-400">
                  Clean text format without formatting tags
                </p>
              </div>
            </div>
            <Download className="w-4 h-4 text-slate-400 group-hover:text-brand-500 transition-colors" />
          </button>

          <button
            type="button"
            onClick={handleDownloadJson}
            className="w-full flex items-center justify-between p-4 rounded-2xl bg-slate-50 hover:bg-brand-50/50 dark:bg-slate-800/60 dark:hover:bg-brand-950/30 border border-slate-200/80 dark:border-slate-700 hover:border-brand-400 transition-all text-left group"
          >
            <div className="flex items-center space-x-3.5">
              <div className="w-10 h-10 rounded-xl bg-purple-100 dark:bg-purple-950/60 text-purple-600 dark:text-purple-400 flex items-center justify-center">
                <FileJson className="w-5 h-5" />
              </div>
              <div>
                <p className="text-sm font-bold text-slate-900 dark:text-white group-hover:text-brand-600 dark:group-hover:text-brand-400 transition-colors">
                  Structured JSON (.json)
                </p>
                <p className="text-xs text-slate-500 dark:text-slate-400">
                  Full programmatic metadata, arrays, and parsed schema
                </p>
              </div>
            </div>
            <Download className="w-4 h-4 text-slate-400 group-hover:text-brand-500 transition-colors" />
          </button>

          <button
            type="button"
            onClick={handlePrint}
            className="w-full flex items-center justify-between p-4 rounded-2xl bg-slate-50 hover:bg-brand-50/50 dark:bg-slate-800/60 dark:hover:bg-brand-950/30 border border-slate-200/80 dark:border-slate-700 hover:border-brand-400 transition-all text-left group"
          >
            <div className="flex items-center space-x-3.5">
              <div className="w-10 h-10 rounded-xl bg-amber-100 dark:bg-amber-950/60 text-amber-600 dark:text-amber-400 flex items-center justify-center">
                <Printer className="w-5 h-5" />
              </div>
              <div>
                <p className="text-sm font-bold text-slate-900 dark:text-white group-hover:text-brand-600 dark:group-hover:text-brand-400 transition-colors">
                  Print / Save as PDF
                </p>
                <p className="text-xs text-slate-500 dark:text-slate-400">
                  Open browser print dialog to save as formatted PDF
                </p>
              </div>
            </div>
            <Printer className="w-4 h-4 text-slate-400 group-hover:text-brand-500 transition-colors" />
          </button>
        </div>

        {/* Footer */}
        <div className="px-6 py-4 bg-slate-50 dark:bg-slate-950 border-t border-slate-100 dark:border-slate-800 flex items-center justify-between">
          <button
            type="button"
            onClick={handleCopyReport}
            className="inline-flex items-center space-x-1.5 text-xs font-semibold text-brand-600 dark:text-brand-400 hover:underline"
          >
            {copied ? (
              <>
                <Check className="w-3.5 h-3.5 text-emerald-500" />
                <span className="text-emerald-600">Copied to Clipboard!</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5" />
                <span>Copy Full Report Text</span>
              </>
            )}
          </button>

          <button
            type="button"
            onClick={onClose}
            className="px-4 py-2 text-xs font-medium text-slate-600 dark:text-slate-400 hover:bg-slate-200 dark:hover:bg-slate-800 rounded-xl transition-colors"
          >
            Close
          </button>
        </div>

      </div>
    </div>
  );
}
