import React, { useState } from 'react';
import {
  Download,
  FileText,
  FileCode,
  Printer,
  Copy,
  Check,
  X,
  FileJson,
} from 'lucide-react';

export default function ExportModal({ isOpen, onClose, data }) {
  const [copied, setCopied] = useState(false);

  if (!isOpen || !data) return null;

  const { metadata, summary, summary_length, key_points, main_ideas, improvement_suggestions } = data;

  const generateMarkdown = () => {
    return `# Document Analysis Report: ${metadata?.filename || 'Document'}

**Generated By:** Document Intelligence Workspace (AI-Powered)  
**File Type:** ${metadata?.file_type?.toUpperCase()}  
**Word Count:** ${metadata?.word_count || 0}  
**Summary Mode:** ${summary_length?.toUpperCase() || 'MEDIUM'}  

---

## 1. Executive Summary
${summary}

---

## 2. Key Points
${(key_points || []).map((pt, i) => `${i + 1}. ${pt}`).join('\n')}

---

## 3. Main Ideas & Document Sections
${(main_ideas || []).map((idea) => `### ${idea.title}\n${idea.summary}\n`).join('\n')}

---

## 4. Improvement Suggestions
${(improvement_suggestions || [])
  .map(
    (sug) =>
      `- **[${sug.category?.toUpperCase() || 'GENERAL'}]** (${sug.severity?.toUpperCase()} priority): ${sug.suggestion}`
  )
  .join('\n')}
`;
  };

  const downloadFile = (content, filename, type) => {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleDownloadMarkdown = () => {
    const md = generateMarkdown();
    const baseName = (metadata?.filename || 'summary').replace(/\.[^/.]+$/, '');
    downloadFile(md, `${baseName}_summary.md`, 'text/markdown;charset=utf-8;');
  };

  const handleDownloadTxt = () => {
    const md = generateMarkdown();
    const baseName = (metadata?.filename || 'summary').replace(/\.[^/.]+$/, '');
    downloadFile(md, `${baseName}_summary.txt`, 'text/plain;charset=utf-8;');
  };

  const handleDownloadJson = () => {
    const jsonStr = JSON.stringify(data, null, 2);
    const baseName = (metadata?.filename || 'summary').replace(/\.[^/.]+$/, '');
    downloadFile(jsonStr, `${baseName}_analysis.json`, 'application/json;charset=utf-8;');
  };

  const handlePrint = () => {
    window.print();
  };

  const handleCopyReport = () => {
    const md = generateMarkdown();
    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-zinc-950/60 backdrop-blur-sm animate-fade-in">
      <div className="bg-white dark:bg-zinc-900 rounded-2xl shadow-elevated border border-zinc-200 dark:border-zinc-800 w-full max-w-lg overflow-hidden">
        
        {/* Header */}
        <div className="px-6 py-4 border-b border-zinc-100 dark:border-zinc-800 flex items-center justify-between">
          <div className="flex items-center space-x-2.5">
            <div className="w-7 h-7 rounded-lg bg-zinc-100 dark:bg-zinc-800 text-zinc-900 dark:text-white flex items-center justify-center">
              <Download className="w-3.5 h-3.5" />
            </div>
            <h3 className="text-sm font-semibold text-zinc-950 dark:text-white">
              Export Analysis Report
            </h3>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded-lg text-zinc-400 hover:text-zinc-600 dark:hover:text-zinc-200 transition-colors"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Options List */}
        <div className="p-6 space-y-2.5">
          <button
            type="button"
            onClick={handleDownloadMarkdown}
            className="w-full flex items-center justify-between p-3.5 rounded-xl bg-zinc-50 hover:bg-zinc-100/80 dark:bg-zinc-800/40 dark:hover:bg-zinc-800 border border-zinc-200/80 dark:border-zinc-700/80 transition-all text-left group"
          >
            <div className="flex items-center space-x-3">
              <div className="w-8 h-8 rounded-lg bg-zinc-100 dark:bg-zinc-800 text-zinc-700 dark:text-zinc-300 flex items-center justify-center">
                <FileText className="w-4 h-4" />
              </div>
              <div>
                <p className="text-xs sm:text-sm font-semibold text-zinc-900 dark:text-white">
                  Markdown Document (.md)
                </p>
                <p className="text-[11px] text-zinc-500 dark:text-zinc-400">
                  Formatted for Notion, Obsidian, GitHub, or docs
                </p>
              </div>
            </div>
            <Download className="w-4 h-4 text-zinc-400 group-hover:text-zinc-700 dark:group-hover:text-zinc-200 transition-colors" />
          </button>

          <button
            type="button"
            onClick={handleDownloadTxt}
            className="w-full flex items-center justify-between p-3.5 rounded-xl bg-zinc-50 hover:bg-zinc-100/80 dark:bg-zinc-800/40 dark:hover:bg-zinc-800 border border-zinc-200/80 dark:border-zinc-700/80 transition-all text-left group"
          >
            <div className="flex items-center space-x-3">
              <div className="w-8 h-8 rounded-lg bg-zinc-100 dark:bg-zinc-800 text-zinc-700 dark:text-zinc-300 flex items-center justify-center">
                <FileCode className="w-4 h-4" />
              </div>
              <div>
                <p className="text-xs sm:text-sm font-semibold text-zinc-900 dark:text-white">
                  Plain Text File (.txt)
                </p>
                <p className="text-[11px] text-zinc-500 dark:text-zinc-400">
                  Clean text format without markdown tags
                </p>
              </div>
            </div>
            <Download className="w-4 h-4 text-zinc-400 group-hover:text-zinc-700 dark:group-hover:text-zinc-200 transition-colors" />
          </button>

          <button
            type="button"
            onClick={handleDownloadJson}
            className="w-full flex items-center justify-between p-3.5 rounded-xl bg-zinc-50 hover:bg-zinc-100/80 dark:bg-zinc-800/40 dark:hover:bg-zinc-800 border border-zinc-200/80 dark:border-zinc-700/80 transition-all text-left group"
          >
            <div className="flex items-center space-x-3">
              <div className="w-8 h-8 rounded-lg bg-zinc-100 dark:bg-zinc-800 text-zinc-700 dark:text-zinc-300 flex items-center justify-center">
                <FileJson className="w-4 h-4" />
              </div>
              <div>
                <p className="text-xs sm:text-sm font-semibold text-zinc-900 dark:text-white">
                  Structured JSON (.json)
                </p>
                <p className="text-[11px] text-zinc-500 dark:text-zinc-400">
                  Full metadata, key points array, and schema
                </p>
              </div>
            </div>
            <Download className="w-4 h-4 text-zinc-400 group-hover:text-zinc-700 dark:group-hover:text-zinc-200 transition-colors" />
          </button>

          <button
            type="button"
            onClick={handlePrint}
            className="w-full flex items-center justify-between p-3.5 rounded-xl bg-zinc-50 hover:bg-zinc-100/80 dark:bg-zinc-800/40 dark:hover:bg-zinc-800 border border-zinc-200/80 dark:border-zinc-700/80 transition-all text-left group"
          >
            <div className="flex items-center space-x-3">
              <div className="w-8 h-8 rounded-lg bg-zinc-100 dark:bg-zinc-800 text-zinc-700 dark:text-zinc-300 flex items-center justify-center">
                <Printer className="w-4 h-4" />
              </div>
              <div>
                <p className="text-xs sm:text-sm font-semibold text-zinc-900 dark:text-white">
                  Print / Save as PDF
                </p>
                <p className="text-[11px] text-zinc-500 dark:text-zinc-400">
                  Open formatted print dialog for export
                </p>
              </div>
            </div>
            <Printer className="w-4 h-4 text-zinc-400 group-hover:text-zinc-700 dark:group-hover:text-zinc-200 transition-colors" />
          </button>
        </div>

        {/* Footer */}
        <div className="px-6 py-3.5 bg-zinc-50/80 dark:bg-zinc-950/80 border-t border-zinc-100 dark:border-zinc-800 flex items-center justify-between">
          <button
            type="button"
            onClick={handleCopyReport}
            className="inline-flex items-center space-x-1.5 text-xs font-medium text-zinc-700 dark:text-zinc-300 hover:text-zinc-950 dark:hover:text-white transition-colors"
          >
            {copied ? (
              <>
                <Check className="w-3.5 h-3.5 text-emerald-500" />
                <span className="text-emerald-600 dark:text-emerald-400">Copied to Clipboard</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5" />
                <span>Copy Full Report</span>
              </>
            )}
          </button>

          <button
            type="button"
            onClick={onClose}
            className="px-3.5 py-1.5 text-xs font-medium text-zinc-600 dark:text-zinc-400 hover:bg-zinc-200 dark:hover:bg-zinc-800 rounded-xl transition-colors"
          >
            Close
          </button>
        </div>

      </div>
    </div>
  );
}
